---
title: "Data exploration"
author: "Ward Langeraert"
date: today
date-format: "D MMMM YYYY"
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
editor_options: 
  chunk_output_type: console
---

# Goal

Data exploration.

```{r}
#| warning: false
#| message: false
# Packages
library(tidyverse)

# Conflicts
conflicted::conflicts_prefer(dplyr::filter)

# Paths
interim_path <- here::here("data", "intermediate")
data_path <- here::here("data", "processed")
```

# Load data

Load observation data of pollinator groups.

```{r}
poll_groups <- c("bees", "butterflies", "moths", "hoverflies")

# Read the files and build a named list
pollinator_obs_df <- lapply(
  file.path(data_path, paste0(poll_groups, "_data.csv")),
  read_csv,
  show_col_types = FALSE
)
names(pollinator_obs_df) <- poll_groups
```

# Univariate

Number of observations per pollinator group.

```{r}
bind_rows(pollinator_obs_df) %>%
  count(pollinatorGroup) %>%
  ggplot(aes(x = pollinatorGroup, y = n)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = n), vjust = -0.25) +
  labs(x = "", y = "Number of observations") +
  theme_minimal()
```

Number of species per pollinator group.

```{r}
bind_rows(pollinator_obs_df) %>%
  group_by(pollinatorGroup) %>%
  summarise(n_spec = n_distinct(species), .groups = "drop") %>%
  ggplot(aes(x = pollinatorGroup, y = n_spec)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = n_spec), vjust = -0.25) +
  labs(x = "", y = "Number of species") +
  theme_minimal()
```

# Bivariate
## Categorical
### Habitat class

### Soil class

## Continuous
### Size of habitat parcels

### Climate variables
